nodes:
- input.visual:
    # source: https://storage.googleapis.com/peekingduck/videos/wave.mp4
    source: pushup.mp4
- model.yolox
- model.posenet
- draw.poses   
- dabble.fps
- custom_nodes.dabble.pushup
- draw.legend:
    show: ["fps"]
- output.screen
- output.media_writer:
    output_dir: C:\Users\hwadr\pose_estimation\save
