nodes:
- input.visual:
    source: "test_data/plank.mp4"
- model.posenet:
    score_threshold: 0.2
- dabble.fps
- custom_nodes.dabble.planks
- draw.poses
- draw.legend:
    show: ["fps", "plank_info", "cumilated_time"]
- output.media_writer:
    output_dir: "output"
- custom_nodes.output.sqlite