nodes:
- input.visual:
    source: "test_data/plank 2.mp4"
- model.yolo
- model.posenet:
    score_threshold: 0.2
- dabble.fps
- custom_nodes.dabble.wave
- draw.poses
- draw.legend:
    show: ["fps", "plank_info"]
- output.screen
- custom_nodes.output.sqlite